name: circle_flags
description: A collection of flags in SVG format (very small in size) with a default rounded shape (which can be customized).
version: 3.0.2
repository: https://github.com/cedvdb/flutter_circle_flags

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  dart_countries: ^3.0.3

flutter:
  assets:
    - assets/svg/
